OrganizationName: SummitDemox
PersonalAccessToken: 8Ww6yekXdFLXSRP0MBriY84cjHbgXRlFINbqi2v4zjIvtjggMrx3JQQJ99BAACAAAAAZ7R1HAAASAZDOAr0u
ProjectName: mTest
AgentPoolName: DSC
BuildAgents:
  UserName: worker
  Password: <Password>
  AzureLocation: West Europe
  AzureRoleSize: Standard_D4ls_v5

